/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAlert: typeof import('ant-design-vue/es')['Alert']
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACardMeta: typeof import('ant-design-vue/es')['CardMeta']
    AComment: typeof import('ant-design-vue/es')['Comment']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AlbomItem: typeof import('./src/components/Albom/AlbomItem.vue')['default']
    AlbomTableHeader: typeof import('./src/components/Albom/AlbomTableHeader.vue')['default']
    AlbumList: typeof import('./src/components/Albom/AlbumList.vue')['default']
    AlertError: typeof import('./src/components/Login/Base/AlertError.vue')['default']
    AlertSuccess: typeof import('./src/components/Login/Base/AlertSuccess.vue')['default']
    AlertWarning: typeof import('./src/components/Login/Base/AlertWarning.vue')['default']
    AList: typeof import('ant-design-vue/es')['List']
    AListItem: typeof import('ant-design-vue/es')['ListItem']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ARate: typeof import('ant-design-vue/es')['Rate']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    ATypographyParagraph: typeof import('ant-design-vue/es')['TypographyParagraph']
    AudioPlayer: typeof import('./src/components/AudioPlayer.vue')['default']
    CommentField: typeof import('./src/components/Comment/CommentField.vue')['default']
    FormField: typeof import('./src/components/Login/Base/FormField.vue')['default']
    LoginField: typeof import('./src/components/Login/LoginField.vue')['default']
    Rate: typeof import('./src/components/Rate.vue')['default']
    RegistrationField: typeof import('./src/components/Login/RegistrationField.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Table: typeof import('./src/components/Table.vue')['default']
    TrackList: typeof import('./src/components/TrackList.vue')['default']
  }
}
